### ISSUE TITLE
Can't run the code

### ISSUE THREAD

**Issue by shaygeller** [ujjax/fast-slow-lstm#1]
Hi,

Thanks for implementing the FSLSTM code in Pytorch.
I'm pretty new to Pytorch and I encountered a problem when running your code. (log is provided below)
Do you have a newer version of this code?

Here is the log:

C:\Users\User\Anaconda3\envs\ml1\python.exe D:/git/pytorch-fast-slow-lstm/main.py
Vocabulary size: 51
########## Training ##########################
torch.Size([128, 256]) shape of x
torch.Size([128, 700]) shape of h
Traceback (most recent call last):
  File "D:/git/pytorch-fast-slow-lstm/main.py", line 126, in <module>
    train_p = run_epoch(model, train_data, True, lr)
  File "D:/git/pytorch-fast-slow-lstm/main.py", line 89, in run_epoch
    outputs, hidden = model(inputs)
  File "C:\Users\User\Anaconda3\envs\ml1\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:/git/pytorch-fast-slow-lstm/main.py", line 57, in forward
    out , state = self.FS_cell(inputs[:,time_step,:],state)
  File "D:\git\pytorch-fast-slow-lstm\FSRNN.py", line 28, in __call__
    F_output, F_state = self.fast_cells[0](inputs, F_state)
  File "D:\git\pytorch-fast-slow-lstm\LNLSTM.py", line 45, in __call__
    concat = np.concatenate((x,h), axis = 1)
  File "C:\Users\User\Anaconda3\envs\ml1\lib\site-packages\torch\tensor.py", line 450, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

**Comment by ChengJianjia** [comment]
Have you solved this problem？I have the same problem.Can you share method if you solve it
